/*
 * NAMA  : Fiona Avila Putri
 * NIM   : 10119013
 * KELAS : IF1 2019/2020 (PBO1)
 */
package com.fionaavila.latihanmvcjdbc.view;

import com.fionaavila.latihanmvcjdbc.controller.PelangganController;
import com.fionaavila.latihanmvcjdbc.database.BarbershopDatabase;
import com.fionaavila.latihanmvcjdbc.entity.Pelanggan;
import com.fionaavila.latihanmvcjdbc.error.PelangganException;
import com.fionaavila.latihanmvcjdbc.event.PelangganListener;
import com.fionaavila.latihanmvcjdbc.model.PelangganModel;
import javax.swing.JTable;
import javax.swing.JTextField;
import com.fionaavila.latihanmvcjdbc.model.TablePelangganModel;
import com.fionaavila.latihanmvcjdbc.service.PelangganDao;
import java.sql.SQLException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Fiona Avila
 */
public class PelangganView extends javax.swing.JFrame implements PelangganListener, ListSelectionListener{

    /**
     * Creates new form PelangganView
     */
    
    private TablePelangganModel tableModel;
    private PelangganModel model;
    private PelangganController controller;
    
    public PelangganView() {
        tableModel = new TablePelangganModel();
        
        model = new PelangganModel();
        model.setListener(this);
        
        controller = new PelangganController();
        controller.setModel(model);
        
        initComponents();
        
        pelangganTable.getSelectionModel().addListSelectionListener(this);
        
        pelangganTable.setModel(tableModel);
    }

    public JTextField getAlamatField() {
        return alamatField;
    }

    public void setAlamatField(JTextField alamatField) {
        this.alamatField = alamatField;
    }

    public JTextField getEmailField() {
        return emailField;
    }

    public void setEmailField(JTextField emailField) {
        this.emailField = emailField;
    }

    public JTextField getIdField() {
        return idField;
    }

    public void setIdField(JTextField idField) {
        this.idField = idField;
    }

    public JTextField getNamaField() {
        return namaField;
    }

    public void setNamaField(JTextField namaField) {
        this.namaField = namaField;
    }

    public JTable getPelangganTable() {
        return pelangganTable;
    }

    public void setPelangganTable(JTable pelangganTable) {
        this.pelangganTable = pelangganTable;
    }

    public JTextField getTeleponField() {
        return teleponField;
    }

    public void setTeleponField(JTextField teleponField) {
        this.teleponField = teleponField;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judulLabel = new javax.swing.JLabel();
        namaTokoLabel = new javax.swing.JLabel();
        alamatTokoLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        teleponLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        namaField = new javax.swing.JTextField();
        alamatField = new javax.swing.JTextField();
        teleponField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        hapusButton = new javax.swing.JButton();
        ubahButton = new javax.swing.JButton();
        tambahButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        pelangganScrollPane = new javax.swing.JScrollPane();
        pelangganTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Design Preview [PelangganView]");

        jPanel1.setToolTipText("");

        judulLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        judulLabel.setText("MANAGEMENT DATA PELANGGAN");

        namaTokoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        namaTokoLabel.setText("FIONA BARBERSHOP");

        alamatTokoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alamatTokoLabel.setText("Jalan Pasar Malintang Dalam No. 3 Padang");

        idLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idLabel.setText("ID :");

        namaLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        namaLabel.setText("NAMA :");

        alamatLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alamatLabel.setText("ALAMAT :");

        teleponLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        teleponLabel.setText("TELEPON :");

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailLabel.setText("EMAIL :");

        idField.setEditable(false);

        hapusButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hapusButton.setText("HAPUS");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        ubahButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ubahButton.setText("UBAH");
        ubahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahButtonActionPerformed(evt);
            }
        });

        tambahButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tambahButton.setText("TAMBAH");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        pelangganTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pelangganScrollPane.setViewportView(pelangganTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(alamatTokoLabel)
                            .addComponent(namaTokoLabel)
                            .addComponent(judulLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(idLabel)
                                    .addComponent(teleponLabel)
                                    .addComponent(namaLabel)
                                    .addComponent(alamatLabel)
                                    .addComponent(emailLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alamatField)
                                    .addComponent(emailField)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(teleponField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(129, 129, 129))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(resetButton)
                        .addGap(18, 18, 18)
                        .addComponent(tambahButton)
                        .addGap(18, 18, 18)
                        .addComponent(ubahButton)
                        .addGap(18, 18, 18)
                        .addComponent(hapusButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pelangganScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(judulLabel)
                .addGap(4, 4, 4)
                .addComponent(namaTokoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamatTokoLabel)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatLabel)
                    .addComponent(alamatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teleponLabel)
                    .addComponent(teleponField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(pelangganScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapusButton)
                    .addComponent(ubahButton)
                    .addComponent(tambahButton)
                    .addComponent(resetButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        controller.resetPelanggan(this);
    }                                           

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        controller.insertPelanggan(this);
    }                                            

    private void ubahButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        controller.updatePelanggan(this);
    }                                          

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        controller.deletePelanggan(this);
    }                                           

    // Variables declaration - do not modify                     
    private javax.swing.JTextField alamatField;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JLabel alamatTokoLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton hapusButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel namaTokoLabel;
    private javax.swing.JScrollPane pelangganScrollPane;
    private javax.swing.JTable pelangganTable;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton tambahButton;
    private javax.swing.JTextField teleponField;
    private javax.swing.JLabel teleponLabel;
    private javax.swing.JButton ubahButton;
    // End of variables declaration                   

    @Override
    public void onChange(PelangganModel model) {
        idField.setText(model.getId()+"");
        namaField.setText(model.getNama());
        alamatField.setText(model.getAlamat());
        teleponField.setText(model.getTelepon());
        emailField.setText(model.getEmail());
    }

    @Override
    public void onInsert(Pelanggan pelanggan) {
        tableModel.add(pelanggan);
    }

    @Override
    public void onDelete() {
        int index = pelangganTable.getSelectedRow();
        tableModel.remove(index);
    }

    @Override
    public void onUpdate(Pelanggan pelanggan) {
        int index = pelangganTable.getSelectedRow();
        tableModel.set(index, pelanggan);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try{
            Pelanggan model = tableModel.get(pelangganTable.getSelectedRow());
            idField.setText(model.getId()+"");
            namaField.setText(model.getNama());
            alamatField.setText(model.getAlamat());
            teleponField.setText(model.getTelepon());
            emailField.setText(model.getEmail());
        }catch(IndexOutOfBoundsException exception){
        }
    }
    
    public void loadDatabase() throws SQLException, PelangganException{
        PelangganDao dao = BarbershopDatabase.getPelangganDao();
        tableModel.setList(dao.selectAllPelanggan());
    }
}
